CREATE TABLESPACE PROJETO_FINAL
DATAFILE 'C:\Users\Rafael\Desktop\Fatec\ADS4\Banco-de-Dados\projeto_final.dbf' SIZE 1M
AUTOEXTEND ON;

CREATE USER RAFAEL
IDENTIFIED BY ALUNO
DEFAULT TABLESPACE PROJETO_FINAL
QUOTA UNLIMITED ON PROJETO_FINAL;

GRANT DBA TO RAFAEL WITH ADMIN OPTION;

----------------------------------------


--CREATE TABLE PARCEIRO_COMERCIAL (
--PARC_PJ VARCHAR(20),
--COD_FORN VARCHAR(5),
--COD_CLIENTE VARCHAR(5),

--CONSTRAINT FK_COD_FORN FOREIGN KEY(COD_FORN) REFERENCES CLIENTE
--);

CREATE TABLE ENDERECO (
COD_ENDERECO NUMBER PRIMARY KEY NOT NULL,
LOGRADOURO VARCHAR(100),
NUMERO VARCHAR(5),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(20),
CEP VARCHAR(10)
);

CREATE TABLE CLIENTE (
COD_CLIENTE NUMBER PRIMARY KEY NOT NULL,
NOME_CLIENTE VARCHAR(100),
CPF_CLIENTE VARCHAR(15) UNIQUE,
INSCRICAO_ESTADUAL_CLIENTE VARCHAR(15) UNIQUE,
CNPJ_CLIENTE VARCHAR(20) UNIQUE,
BLOQ_CLIENTE NUMBER(1),
LIMITE_COMPRA_CLIENTE NUMBER(5),
DESCRICAO_CLIENTE VARCHAR(200),
FORMA_PAGAMENTO_CLIENTE VARCHAR(100),
RAZAO_SOCIAL_CLIENTE VARCHAR(10),
ENDERECO_CLIENTE NUMBER,

CONSTRAINT CK_BLOQ_CLIENTE CHECK(BLOQ_CLIENTE IN(0,1)),
CONSTRAINT FK_ENDERECO_CLIENTE FOREIGN KEY(ENDERECO_CLIENTE) REFERENCES ENDERECO(COD_ENDERECO)
);

CREATE TABLE FORNECEDOR (
COD_FORN NUMBER PRIMARY KEY NOT NULL,
NOME_FORN VARCHAR(100),
CPF_FORN VARCHAR(15) UNIQUE,
INSCRICAO_ESTADUAL_FORN VARCHAR(15) UNIQUE,
CNPJ_FORN VARCHAR(20) UNIQUE,
BLOQ_FORN NUMBER(1),
DESCRICAO_FORN VARCHAR,
FORMA_PAGAMENTO_FORN VARCHAR,
RAZAO_SOCIAL_FORN VARCHAR(10),
ENDERECO_FORN NUMBER,

CONSTRAINT CK_BLOQ_FORN CHECK(BLOQ_FORN IN(0,1)),
CONSTRAINT FK_ENDERECO_FORN FOREIGN KEY(ENDERECO_FORN) REFERENCES ENDERECO(COD_ENDERECO)
);

CREATE TABLE COMPRA (
COD_COMPRA NUMBER PRIMARY KEY NOT NULL,
COMPRA_DATA DATE,
COMPRA_QTDE NUMBER,
COMPRA_NFE_ENTRADA VARCHAR(20),
COD_FORN NUMBER,

CONSTRAINT FK_COD_FORN FOREIGN KEY(COD_FORN) REFERENCES FORNECEDOR(COD_FORN)
);

CREATE TABLE ESTOQUE_PRODUTO (
PROD_COD NUMBER PRIMARY KEY NOT NULL,
ESTOQUE_QTDE_ATUAL NUMBER,
ESTOQUE_QTDE_MINIMA NUMBER,
ESTOQUE_PROD_VALIDADE DATE,
ESTOQUE_DATA_INVENTARIO DATE,
ESTOQUE_INVENTARIO NUMBER,
DATA_DISPONIBILIZACAO DATE,
PROD_DESC VARCHAR(50),
PROD_PESO NUMBER(4,2),
PROD_DIMENSAO VARCHAR(15),
PROD_PRECO_CUSTO NUMBER(6,2),
PROD_PRECO_VENDA NUMBER(6,2),
PROD_PRECO_FORN NUMBER(6,2),
PROD_PERC_LUCRO NUMBER(3,1)
);


CREATE TABLE VENDA (
COD_VENDA NUMBER PRIMARY KEY NOT NULL,
VENDA_DATA DATE,
VENDA_QTDE NUMBER,
VENDA_NFE_SAIDA VARCHAR(20),
VENDA_FRETE_ESTIMADO NUMBER(6,2),
COD_CLIENTE NUMBER,

CONSTRAINT FK_COD_CLIENTE FOREIGN KEY(COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE)
);

CREATE TABLE PRODUTO_COMPRADO (
PROD_QTDE_COMP NUMBER,
PROD_VALOR_COMP NUMBER(6,2),
COD_COMPRA NUMBER,
COD_PROD NUMBER,

CONSTRAINT PK_COD_COMPRA_COD_PROD PRIMARY KEY(COD_COMPRA,COD_PROD),
CONSTRAINT FK_COD_COMPRA FOREIGN KEY(COD_COMPRA) REFERENCES COMPRA(COD_COMPRA),
CONSTRAINT FK_COD_PROD_COMP FOREIGN KEY(COD_PROD) REFERENCES ESTOQUE_PRODUTO(PROD_COD)

);



CREATE TABLE PRODUTO_VENDIDO (
PROD_QTDE_VEND VARCHAR(6),
PROD_VALOR_VEND NUMBER(6,2),
VENDA_NFE_SAIDA NUMBER,
COD_VENDA NUMBER,
COD_PROD NUMBER,

CONSTRAINT PK_COD_VENDA_COD_PROD PRIMARY KEY(COD_VENDA, COD_PROD),
CONSTRAINT FK_COD_VENDA FOREIGN KEY(COD_VENDA) REFERENCES VENDA(COD_VENDA),
CONSTRAINT FK_COD_PROD_VEND FOREIGN KEY(COD_PROD) REFERENCES ESTOQUE_PRODUTO(PROD_COD)

);


---------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------
CREATE SEQUENCE SEQ_ENDERECO;
INSERT INTO ENDERECO(COD_ENDERECO, LOGRADOURO, NUMERO, BAIRRO, CIDADE, ESTADO, CEP) VALUES (
SEQ_ENDERECO.NEXTVAL,
'Rua Lacerda Franco',
'834',
'Cambuci',
'Sao Paulo',
'Sao Paulo',
'11223-276'
);

SELECT * FROM ENDERECO;
--do cod_endereco 22 em diante sao para os clientes

---------------------------------------------------------------------------------------------------------------
CREATE SEQUENCE SEQ_FORNECEDOR;
INSERT INTO FORNECEDOR(COD_FORN, NOME_FORN, CPF_FORN, INSCRICAO_ESTADUAL_FORN, CNPJ_FORN, BLOQ_FORN,
DESCRICAO_FORN, FORMA_PAGAMENTO_FORN, RAZAO_SOCIAL_FORN, ENDERECO_FORN) VALUES (
SEQ_FORNECEDOR.NEXTVAL,
'Dore Mifa Clone',
'',
'352.452.552.152',
'302.402.502.102',
0,
'Instrumentos Musicais e Acessorios',
'Cartao Debito',
'Dore Mifa Ltda',
NULL
);



SELECT * FROM FORNECEDOR;

UPDATE FORNECEDOR SET RAZAO_SOCIAL_FORN = 'Sunburn Ltda' WHERE NOME_FORN = 'Sunburn';

ALTER TABLE FORNECEDOR MODIFY (RAZAO_SOCIAL_FORN VARCHAR(30));

SELECT * FROM FORNECEDOR, ENDERECO WHERE FORNECEDOR.ENDERECO_FORN = ENDERECO.COD_ENDERECO;

DELETE FROM FORNECEDOR WHERE COD_FORN = 2;

-----------------------------------------------------------------------------------------------------------------
CREATE SEQUENCE SEQ_COMPRA;
INSERT INTO COMPRA(COD_COMPRA, COMPRA_DATA, COMPRA_QTDE, COMPRA_NFE_ENTRADA, COD_FORN) VALUES (
SEQ_COMPRA.NEXTVAL,
TO_DATE('14 JUL-2015','DD-MON-YYYY'),
600,
'02238858-21',
19
);

SELECT * FROM COMPRA;

COMMIT;



--DROP TABLE PRODUTO_COMPRADO;
--DROP TABLE COMPRA;
--DROP TABLE PRODUTO_VENDIDO;
--DROP TABLE VENDA;

-----------------------------------------------------------------------------------------------------------------

CREATE SEQUENCE SEQ_CLIENTE;
INSERT INTO CLIENTE(COD_CLIENTE, NOME_CLIENTE, CPF_CLIENTE, INSCRICAO_ESTADUAL_CLIENTE, CNPJ_CLIENTE, BLOQ_CLIENTE,
LIMITE_COMPRA_CLIENTE, DESCRICAO_CLIENTE, FORMA_PAGAMENTO_CLIENTE, RAZAO_SOCIAL_CLIENTE, ENDERECO_CLIENTE) VALUES (
SEQ_CLIENTE.NEXTVAL,
'Maria',
'023023023.02',
'',
'',
0,
0,
'Pessoa Fisica',
'Cartao Credito',
'',
35
);

SELECT * FROM CLIENTE;

UPDATE CLIENTE SET ENDERECO_CLIENTE = 34 WHERE COD_CLIENTE = 16;

COMMIT;
---------------------------------------------------------------------------------------------------------------------
CREATE SEQUENCE SEQ_PROD;

RENAME COLUMN ESTOQUE_PRODUTO.PROD_COD TO COD_PROD;

INSERT INTO ESTOQUE_PRODUTO(PROD_COD, ESTOQUE_QTDE_ATUAL, ESTOQUE_QTDE_MINIMA, ESTOQUE_PROD_VALIDADE, ESTOQUE_DATA_INVENTARIO,
ESTOQUE_INVENTARIO, DATA_DISPONIBILIZACAO, PROD_DESC, PROD_PESO, PROD_DIMENSAO, PROD_PRECO_CUSTO, PROD_PRECO_VENDA,
PROD_PRECO_FORN, PROD_PERC_LUCRO) VALUES (
SEQ_PROD.NEXTVAL,
500,
50,
TO_DATE('21-OCT-2021','DD-MON-YYYY'),
TO_DATE('21-OCT-2019','DD-MON-YYYY'),
20,
TO_DATE('21-JAN-2011','DD-MON-YYYY'),
'Suplemento Whey Protein',
0,
'',
15,
20.50,
15,
10
);

SELECT * FROM ESTOQUE_PRODUTO;

UPDATE ESTOQUE_PRODUTO SET PROD_DIMENSAO = '' WHERE PROD_COD = 1;

COMMIT;

--------------------------------------------------------------------------------------------------------------------
CREATE SEQUENCE SEQ_VENDA;
INSERT INTO VENDA(COD_VENDA, VENDA_DATA, VENDA_QTDE, VENDA_NFE_SAIDA, VENDA_FRETE_ESTIMADO, COD_CLIENTE) VALUES (
SEQ_VENDA.NEXTVAL,
TO_DATE('21-MAY-2020','DD-MON-YYYY'),
1,
'00100-2',
15,
18
);

SELECT * FROM VENDA;

UPDATE VENDA SET COD_CLIENTE = 4 WHERE COD_VENDA = 4;

COMMIT;
--------------------------------------------------------------------------------------------------------------

SELECT * FROM PRODUTO_COMPRADO;

CREATE SEQUENCE SEQ_COD_PROD;
INSERT INTO PRODUTO_COMPRADO(PROD_QTDE_COMP, PROD_VALOR_COMP, COD_COMPRA, COD_PROD) VALUES (
26,
26,
35,
SEQ_COD_PROD.NEXTVAL
);

COMMIT;


SELECT * FROM PRODUTO_VENDIDO;

CREATE SEQUENCE SEQ_COD_PROD_VEND;
INSERT INTO PRODUTO_VENDIDO(PROD_QTDE_VEND, PROD_VALOR_VEND, VENDA_NFE_SAIDA, COD_VENDA, COD_PROD) VALUES (
18,
20,
100345,
38,
2
);

COMMIT;

--------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------

-- VIEW
SELECT * FROM ESTOQUE_PRODUTO;

SELECT PROD_DESC, PROD_PRECO_CUSTO, PROD_PRECO_VENDA, PROD_PRECO_FORN FROM ESTOQUE_PRODUTO WHERE PROD_PRECO_VENDA > 25;

CREATE OR REPLACE VIEW PRECOS AS SELECT PROD_DESC, PROD_PRECO_CUSTO, PROD_PRECO_VENDA, PROD_PRECO_FORN
FROM ESTOQUE_PRODUTO WHERE PROD_PRECO_VENDA > 25;

SELECT * FROM PRECOS;

COMMIT;
--------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------

--JOIN
--SELECIONA TODAS INFORMACOES DE FORNECEDOR E ENDERECO
SELECT * FROM FORNECEDOR F, ENDERECO E WHERE F.ENDERECO_FORN = E.COD_ENDERECO;

--INNER JOIN
--SELECIONA TODAS AS INFORMACOES DO FORNECEDOR E O ENDERECO, INCLUINDO OS FORNECEDORES QUE NAO POSSUEM ENDERECO CADASTRADO
SELECT NOME_FORN, DESCRICAO_FORN FROM FORNECEDOR JOIN ENDERECO ON FORNECEDOR.ENDERECO_FORN = ENDERECO.COD_ENDERECO;

--LEFT JOIN
--SELECIONA TODAS AS INFORMACOES DE ENDERECO, INCLUINDO OS ENDERECOS QUE NAO POSSUEM FORNECEDORES VINCULADOS
SELECT NOME_FORN, DESCRICAO_FORN, LOGRADOURO FROM FORNECEDOR LEFT JOIN ENDERECO ON FORNECEDOR.ENDERECO_FORN = ENDERECO.COD_ENDERECO;

--RIGHT JOIN
--SELECIONA INFORMACOES DE FORNECEDOR ENDERECO MESMO QUE NAO TENHA FORNECEDOR CADASTRADO COM ENDERECO
SELECT NOME_FORN, DESCRICAO_FORN, LOGRADOURO FROM FORNECEDOR RIGHT JOIN ENDERECO ON FORNECEDOR.ENDERECO_FORN = ENDERECO.COD_ENDERECO;

--UNION (mesma tabela ou tabelas diferentes em que as colunas sejam compativeis)
--
SELECT * FROM FORNECEDOR;

SELECT * FROM FORNECEDOR
WHERE FORMA_PAGAMENTO_FORN = 'Paypal'
UNION
SELECT * FROM FORNECEDOR
WHERE FORMA_PAGAMENTO_FORN = 'Boleto Bancario';
    
SELECT PROD_VALOR_COMP FROM PRODUTO_COMPRADO
UNION
SELECT PROD_VALOR_VEND FROM PRODUTO_VENDIDO;

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
--GROUP BY
--PEGAR A SOMA DE QUANTIDADE E A SOMA DO VALOR TOTAL SEPARADOS POR CODIGO E DESCRICAO
SELECT * FROM ESTOQUE_PRODUTO;

SELECT COD_PROD, PROD_DESC, SUM(PROD_QTDE_VEND) AS SOMA, SUM(PROD_VALOR_VEND) AS TOTAL FROM ESTOQUE_PRODUTO JOIN PRODUTO_VENDIDO ON PROD_COD = COD_PROD 
GROUP BY
COD_PROD, PROD_DESC
ORDER BY COD_PROD, PROD_DESC;

SELECT SUM(PROD_QTDE_VEND) FROM PRODUTO_VENDIDO;

SELECT SUM(PROD_VALOR_VEND) FROM PRODUTO_VENDIDO;

SELECT COD_PROD, PROD_DESC, SUM(PROD_QTDE_VEND) AS SOMA, SUM(PROD_VALOR_VEND) AS TOTAL FROM ESTOQUE_PRODUTO

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
--HAVING
JOIN PRODUTO_VENDIDO ON PROD_COD = COD_PROD 
GROUP BY
COD_PROD, PROD_DESC
HAVING SUM(PROD_VALOR_VEND) > 15;




------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

--SUBCONSULTA
SELECT * FROM CLIENTE WHERE DESCRICAO_CLIENTE = 'Pessoa Fisica' AND ENDERECO_CLIENTE IN(
SELECT COD_ENDERECO FROM ENDERECO WHERE CIDADE = 'Sao Jose dos Campos');

SELECT * FROM ENDERECO;


COMMIT;